version: '2'

services:
  server:
    image: wnlab/uber-api:v0.0.1
    container_name: fastapi_server
    networks:
      - cloud-native
    restart: always
    ports:
      - "8888:8888"
  db:
    image: wnlab/uber-db:v0.0.1
    restart: unless-stopped
    container_name: cloud_postgresql
    networks:
      - cloud-native
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_volume:
networks:
  cloud-native:

